### ISSUE TITLE
init.d scripts didn't run

### ISSUE THREAD

**Issue by izuannazrin** [Zackptg5/Init.d-Injector#1]
Apparently (at least on my phone), `/system/etc/init.d` is yet to be mounted during post_fs_data. So, it should run scripts from `$MODPATH/system/etc/init.d` instead.

**Comment by Zackptg5** [comment]
Ugh, that's right. Magisk mount mounts everything after post-fs-data scripts runs for some reason. I'll fix it for the next version, thanks!
