### ISSUE TITLE
如何使用？ How to use?

### ISSUE THREAD

**Issue by 873578156** [Zackptg5/Init.d-Injector#3]

**Comment by Zackptg5** [comment]
This isn't the place for support, that's here: https://forum.xda-developers.com/android/software-hacking/mod-universal-init-d-injector-wip-t3692105

And you just flash the zip...

**Comment by dragoonmaster** [comment]
app2sd say after installing your device not have init.d support magisk 18.1 & init.d injacter latest 3.1
